language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
before_install:
  - gem update bundler
gemfile:
  - gemfiles/actionpack_3_2.gemfile
  - gemfiles/actionpack_4_0.gemfile
  - gemfiles/actionview_4_1.gemfile
  - gemfiles/actionview_4_2.gemfile
  - gemfiles/actionview_5_0.gemfile
  - gemfiles/actionview_master.gemfile
matrix:
  exclude:
  - rvm: 2.0.0
      gemfile: gemfiles/actionview_5_0.gemfile
  - rvm: 2.0.0
      gemfile: gemfiles/actionview_master.gemfile
  - rvm: 2.1
      gemfile: gemfiles/actionview_5_0.gemfile
  - rvm: 2.1
      gemfile: gemfiles/actionview_master.gemfile
  - rvm: 2.2
      gemfile: gemfiles/actionview_5_0.gemfile
  - rvm: 2.2
      gemfile: gemfiles/actionview_master.gemfile
