language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0-rc1
gemfile:
  - gemfiles/actionpack_3_2.gemfile
  - gemfiles/actionpack_4_0.gemfile
  - gemfiles/actionview_4_1.gemfile
branches:
  only:
    - master
