language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
before_install:
  - gem update bundler
gemfile:
  - gemfiles/actionpack_3_2.gemfile
  - gemfiles/actionpack_4_0.gemfile
  - gemfiles/actionview_4_1.gemfile
  - gemfiles/actionview_master.gemfile
branches:
  only:
    - master
